#!/usr/bin/env sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
case "${1:-.env}" in
  /*) out=$1 ;;
  *) out="$PWD/${1:-.env}" ;;
esac
cd "$script_dir"

find_cmd() {
  command -v "$1" 2>/dev/null || true
}

first_cmd() {
  for name in "$@"; do
    path="$(find_cmd "$name")"
    if [ -n "$path" ]; then
      printf '%s' "$path"
      return
    fi
  done
  printf '%s' "$1"
}

quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

write_var() {
  printf '%s=%s\n' "$1" "$(quote "$2")"
}

{
  printf '# Generated by init_env.sh. Edit paths here for your machine.\n'
  write_var ENVS_ROOT "$PWD"
  write_var PYTHON "$(first_cmd python3 python)"
  write_var NODE "$(first_cmd node)"
  write_var NPM "$(first_cmd npm)"
  write_var NPM_CACHE "$PWD/.cache/npm"
  write_var JAVASCRIPT_NODE_MODULES ""
  write_var TYPESCRIPT_NODE_MODULES ""
  write_var MAVEN "$(first_cmd mvn)"
  write_var MAVEN_LOCAL_REPO "$PWD/.cache/m2"
  write_var CXX "$(first_cmd g++)"
  write_var CXXFLAGS "-std=c++20 -O2 -pthread"
} > "$out"

printf 'Wrote %s\n' "$out"
